language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rok0sbasilisk/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rok0sbasilisk/docker-react npm run test